[package]
name = "Suzaku"
version = "0.1.0"
repository = "https://github.com/Yamato-Security/suzaku"
authors = ["Yamato Security @SecurityYamato"]
edition = "2024"
rust-version = "1.86.0"
include = ["src/**/*", "LICENSE.txt", "README.md", "CHANGELOG.md"]

[dependencies]
bytesize = "2.*"
chrono = "0.4.*"
clap = {version = "4.5.*", features = ["derive", "env"]}
colored = "2"
comfy-table = "7.*"
console = "0.*"
const_format = "0.2"
csv = "1.3.*"
flate2 = { version = "1.1.*", features = ["zlib-rs"], default-features = false }
git2="*"
hashbrown="*"
indicatif = "*"
krapslog = "0.6"
num-format = "0.4.*"
serde_json = "1.0.*"
sigma-rust = "0.5.*"
termcolor = "*"
terminal_size = "0.4.*"
ureq="*"

[target.'cfg(unix)'.dependencies] #Mac and Linux
openssl = { version = "*", features = ["vendored"] }  #vendored is needed to compile statically.
