[package]
name = "suzaku"
version = "0.0.1"
repository = "https://github.com/Yamato-Security/suzaku"
authors = ["Yamato Security @SecurityYamato"]
edition = "2024"
rust-version = "1.85.0"
include = ["src/**/*", "LICENSE.txt", "README.md", "CHANGELOG.md"]

[dependencies]
clap = {version = "4.5.31", features = ["derive", "env"]}
sigma-rust = "0.5.1"
serde_json = "1.0.139"
flate2 = "1.1.0"
csv = "1.3.*"
