[package]
name = "suzaku"
version = "0.0.1"
repository = "https://github.com/Yamato-Security/suzaku"
authors = ["Yamato Security @SecurityYamato"]
edition = "2024"
rust-version = "1.85.1"
include = ["src/**/*", "LICENSE.txt", "README.md", "CHANGELOG.md"]

[dependencies]
clap = {version = "4.5.*", features = ["derive", "env"]}
sigma-rust = "0.5.*"
serde_json = "1.0.*"
flate2 = { version = "1.1.*", features = ["zlib-rs"], default-features = false }
csv = "1.3.*"
indicatif = "*"
colored = "2"
bytesize = "1.*"
chrono = "0.4.*"
comfy-table = "7.*"
krapslog = "0.6"
terminal_size = "0.4.*"
termcolor = "*"
num-format = "0.4.*"
console = "0.*"
git2="*"
ureq="*"
hashbrown="*"