Timestamp: '.time|.eventTimestamp|.CreationTime'
RuleTitle: 'sigma.title'
Level: 'sigma.level'
Workload: '.Workload'
Operation: '.operationName.value|.operationName|.Operation'
RecordType: '.RecordType'
Result: '.ResultStatus|.resultType'
User: '.caller|.UserId'
SrcIP: '.claims.ipaddr|.callerIpAddress|.ClientIP|.ActorIpAddress'
TargetObject: '.properties.entity|.ObjectId'
UserAgent: '.ExtendedProperties.UserAgent|.DeviceProperties.UserAgent'
AppId: '.ApplicationId|.AppId'
LogonError: '.LogonError'
Details: '._Details'
Category: '.category.value|.category'
CorrelationId: '.correlationId|.CorrelationID'
RuleAuthor: 'sigma.author'
Tags: 'sigma.tags'
RuleID: 'sigma.id'
