Timestamp: '.time'
RuleTitle: 'sigma.title'
RuleAuthor: 'sigma.author'
Level: 'sigma.level'
Category: '.category'
OperationName: '.operationName'
SrcIP: '.callerIpAddress'
ResourceId: '.resourceId'
CorrelationId  : '.correlationId'
RuleID: 'sigma.id'