Timestamp: '.time|.eventTimestamp'
RuleTitle: 'sigma.title'
RuleAuthor: 'sigma.author'
Level: 'sigma.level'
Category: '.category.value|.category'
OperationName: '.operationName.value|.operationName'
Entity: '.properties.entity'
Caller: '.caller'
SrcIP: '.claims.ipaddr|.callerIpAddress'
ResourceId: '.resourceId'
CorrelationId  : '.correlationId'
RuleID: 'sigma.id'